### ISSUE TITLE
Equalized heights larger than expected when using 1.10

### ISSUE THREAD

**Issue by heisRichard** [CSS-Tricks/Equalizer#2]
As the title suggests - just implementing equalizer on a website which is using jq 1.10. whilst the objects are being equalized the height returned is greater than expected. reverting back to 1.9 means all is working correctly.

**Comment by Mottie** [comment]
Hi @heisRichard!

Sorry for taking so long to respond.

LOL I just closed issue number 21... But basically I fixed this issue by correctly parsing the jQuery version number. It should fix any problems. Thanks for your patience.
