### ISSUE TITLE
IE 8 only works on resize.

### ISSUE THREAD

**Issue by engwerda** [CSS-Tricks/Equalizer#4]
I have this working nicely in all browsers I tested except IE 8. 
In IE 8 it only equalizes the  height after resizing the window but not on the initial loading of the page.

Simon

**Comment by Mottie** [comment]
Hi @engwerda!

How are you initializing the plugin? Is it inside of a document ready function:

``` js
$(function() {
  $('.wrapper').equalizer();
});
```

If so, then maybe try initializing it on window load:

``` js
$(window).load(function() {
  $('.wrapper').equalizer();
});
```

or, do it twice - on document ready and window load, to make sure it updates after all images have loaded.

**Comment by engwerda** [comment]
On window load solved my issue. :)

I was initializing it with <a href="http://desandro.github.io/imagesloaded/">imagesLoaded</a> and also tried document ready function.

Thanks for the help!
