### ISSUE TITLE
Deeply flawed by design. Avoid this plugin.

### ISSUE THREAD

**Issue by Jiia** [CSS-Tricks/Equalizer#6]
This plugin is deeply flawed in how it operates. When the plugin runs, it wraps all content inside the target elements inside a wrapper called "equalizer-inner". This wrapper has auto height by default. As it turns out this wrapper element causes all sorts of problems which makes this plugin a waste of your time.

Now imagine if your content has "height: 100%" it will not work anymore as it will only grow to the height of the "equalizer-inner", which is set to auto. This means that 100% height will turn into auto height.

You probably think it would be easy to fix this by setting the height of "equalizer-inner" to 100% or inherit. But the plugin is designed so that if you do this, all equalized elements will get "height: 0px" when resizing the screen.

The entire plugin should be rewritten. I suggest using any other equalizing plugin because this is the only one that adds its own wrappers to your html.

**Comment by Mottie** [comment]
Hi @Jiia!

Thanks for the feedback! This plugin was written before HTML5 and css3 columns came into common use. So it really isn't necessary any more, unless you still want to support older browsers.

While we appreciate feedback, even negative, we appreciate pull requests even more!
